[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["thisisyoojin <thisisyoojin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.7"
psycopg = {extras = ["binary"], version = "^3.2.6"}
django-htmx = "^1.23.0"
pytest = "^8.3.5"
model-bakery = "^1.20.4"
pytest-django = "^4.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "app.settings"
testpaths = ["."]
python_files = ["test_*.py", "*_test.py"]